### ISSUE TITLE
Create Rooks and design their movement

### ISSUE THREAD

**Issue by silvericarus** [silvericarus/just-chess#2]
Their movement is defined by:
They can move in the x and y axis indefinitely until they find another piece.

**Comment by FranciscoJesusGata** [comment]
You should also change bg-color of the cells where the piece can move or eliminate another piece.

Like, yellow for movement and red for eliminate.

**Comment by silvericarus** [comment]
@FranciscoJesusGata I'll make an issue for that. I'm working on the rooks right now.
