### ISSUE TITLE
Switch current landing page

### ISSUE THREAD

**Issue by silvericarus** [silvericarus/just-chess#26]
Currently, the landing page is index.html, change it with listgames.html so it becomes the landing page.

**Comment by silvericarus** [comment]
This would also fix the error `"Document path must be a non-empty string"`, due to it requiring a valid game id that its not passed to the script.

**Comment by BosEriko** [comment]
Hello, I was hoping I could make a PR for this, however, I noticed that your repository is a static site, right? Can I ask where is it hosted?

**Comment by silvericarus** [comment]
Currently, the changes on master branch of the repository can be seen in a Github Page [Here](https://silvericarus.github.io/just-chess/). For making the changes in this issue, maybe just a change in the file names would be enough.
