### ISSUE TITLE
Empty cells are draggable

### ISSUE THREAD

**Issue by FranciscoJesusGata** [silvericarus/just-chess#7]
That causes errors in console and sometimes you drag multiple pieces at the same time.

**Comment by silvericarus** [comment]
Maybe this is caused because the cells itself have a drag property, or maybe because the implicit drag function that images have that overlaps with the drag function I implemented for each piece. Maybe this could be fixed by removing the default drag function of the images.

**Comment by silvericarus** [comment]
Im closing this because it's repeated. The more detailed version is here #13
